---
services:
    parser:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        image: electrodacus-parser
        volumes:
            - ../data:/data:ro
        entrypoint: [electrodacus-parser]
