name: Groq Code Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - "LICENSE"

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Debug event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Ref: ${{ github.ref }}"

      - uses: actions/checkout@v4

      - name: Get diff of the pull request
        id: get_diff
        shell: bash
        env:
          DEFAULT_BRANCH: main
        run: |
          # Fetch the default branch
          git fetch origin "${{ env.DEFAULT_BRANCH }}"

          # Get diff excluding certain file types
          git diff "origin/${{ env.DEFAULT_BRANCH }}" -- ':(exclude)*.png' > "diff.txt"

          # Put multi-line string into an environment variable
          {
            echo "pull_request_diff<<EOF"
            cat "diff.txt"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Groq Code Review
        uses: rajsinghparihar/llm-code-review@0.0.1
        with:
          apiKey: ${{ secrets.GROQ_API_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubRepository: ${{ github.repository }}
          githubPullRequestNumber: ${{ github.event.pull_request.number }}
          gitCommitHash: ${{ github.event.pull_request.head.sha }}
          repoId: "llama3-70b-8192"
          temperature: "0.2"
          maxNewTokens: "256"
          topK: "40"
          topP: "0.95"
          pullRequestDiff: ${{ steps.get_diff.outputs.pull_request_diff }}
          pullRequestChunkSize: "4000"
          logLevel: "DEBUG"
